server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      #eureka高可用
      #defaultZone: http://127.0.0.1:10087/eureka
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  #全局前缀
  prefix: /api
  routes:
    item-service: /item/**
#  routes:
#    user-service:
#      path: /user/**
#      serviceId: user-service
#      #忽略前缀
#      strip-prefix: false
#  #忽略服务，不像前端暴露接口，允许内部调用
#  ignored-services: consumer-service
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 熔断超时时长
ribbon:
  ConnectionTimeout: 1000 #ribbon链接超时时长
  ReadTimeout: 2000  #ribbon读取超市时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数

